### ISSUE TITLE
Not installing on windows.

### ISSUE THREAD

**Issue by fusionstrings** [wakayama-io/generator-hapi-composer#1]
Hi I am trying to install this generator on windows 7 but it is failing.
    `npm ERR! notarget No compatible version found: yeoman-    generator@'youngmountain/generator#dont-store-defaults'`

And installation is failing.
I am running on node JS 0.10.26, NPM v 1.4.3, yo v 1.2.0, hapi 6.0.2.

**Comment by kojiwakayama** [comment]
Hi, it looks like if you are installing from an old develop branch from the github repo and we already merged the branch into the master and removed it. How do you install the generator? Could you try to install the generator from the master branch or from npm? The installation works for me on windows 7 with: npm install -g generator-hapi-composer.

**Comment by fusionstrings** [comment]
Well it's strange,
I was trying `npm install -g generator-hapi-composer` and it failed every time. Although I do remember dependency check was failing earlier.

Anyways now it installed flawlessly and I am good to go. I am loving it so far. All the good luck for making this. Hope it'll keep up with hapi development speed :+1:

**Comment by fusionstrings** [comment]
Well i though I started to party early (immediately it installed).

While creating project using `yo hapi-composer` I am facing following error.
This appear to be problem with one of plugins as it worked with default settings.

   `> heapdump@0.2.9 install D:\Sapient\Projects\hapi-composer\node_modules\poop\node_modules\heapdump
    > node-gyp rebuild

```
D:\Sapient\Projects\hapi-composer\node_modules\poop\node_modules\heapdump>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2
) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\
Sapient\Projects\hapi-composer\node_modules\poop\node_modules\heapdump\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Sapient\Projects\hapi-composer\node_modules\poop\node_modules\heapdump
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! heapdump@0.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.2.9 install script.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\Sapient\Projects\hapi-composer
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Sapient\Projects\hapi-composer\npm-debug.log
npm ERR! not ok code 0
```

**Comment by kojiwakayama** [comment]
which options did you choose and when did the error occur?

**Comment by fusionstrings** [comment]
I selected all the plugins and additional options to try it out. Error occurred during project creation.

**Comment by kojiwakayama** [comment]
Update to the latest version of the generator by running:
npm update -g generator-hapi-composer

Also remove the generator-hapi-composer settings from .yo-rc-global.json which is located in your user home directory before running the generator.

Then make a new project folder and cd into it and rerun the generator:
yo hapi-composer

All features are working for me on OSX. There is an issue with the poop plugin on windows. 
Please open up an issue regarding this at: https://github.com/spumko/poop/issues

**Comment by fusionstrings** [comment]
@kojiwakayama I updated hapi-composer and now immediately after running `yo hapi-composer` I am getting following error.

```
Error: Cannot find module 'npm-latest'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\dshuk4\AppData\Roaming\npm\node_modules\generator-hapi-composer\app\index.js:5:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by kojiwakayama** [comment]
Seems like the installation of the generator didn't complete. Can u npm uninstall -g generator-hapi-composer and reinstall with npm install -g generator-hapi-composer ?

**Comment by fusionstrings** [comment]
yes it worked on fresh install without 'poop'. browserSync integration would be nice to have.
